query GET_LINKEDIN_PROFILES($data: GetLinkedinProfileInput!) {
  getLinkedinProfiles(data: $data) {
    totalCount
    profiles {
      id
      title
      fullName
      company
      location
      createdAt
    }
  }
}
