query GET_GOOGLE_PROFILES($data: GetGoogleInput!) {
  getAllGoogleProfiles(data: $data) {
    totalCount
    profiles {
      id
      company
      rating
      category
      country
      claim_status
      total_reviews
    }
  }
}
